// Template file. The real environment.ts and environment.development.ts
// are auto-generated by scripts/set-env.js at dev/build time.
export const environment = {
    production: false,
    supabaseUrl: 'https://your-project.supabase.co',
    supabaseKey: 'your-anon-public-key'
};
