/**
 * Generates src/environments/environment.ts and environment.development.ts
 * from environment variables. Runs automatically before `npm start` and
 * `npm run build` via the `prestart` and `prebuild` hooks.
 *
 * Locally: values are read from a `.env` file (see `.env.example`).
 * On Netlify: values come from Site settings -> Environment variables.
 */

const fs = require('fs');
const path = require('path');

const envDir = path.join(__dirname, '..', 'src', 'environments');

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error('\n[set-env] Missing required environment variables.');
    console.error('[set-env] Please set SUPABASE_URL and SUPABASE_ANON_KEY.');
    console.error('[set-env] Locally: create a .env file (see .env.example).');
    console.error('[set-env] On Netlify: Site settings -> Environment variables.\n');
    process.exit(1);
}

const buildFile = (production) => `// This file is auto-generated by scripts/set-env.js.
// Do not edit manually. Do not commit.
export const environment = {
    production: ${production},
    supabaseUrl: '${supabaseUrl}',
    supabaseKey: '${supabaseKey}'
};
`;

fs.mkdirSync(envDir, { recursive: true });
fs.writeFileSync(path.join(envDir, 'environment.ts'), buildFile(true));
fs.writeFileSync(path.join(envDir, 'environment.development.ts'), buildFile(false));

console.log('[set-env] Generated environment.ts and environment.development.ts');
